.TH ROOT 1 "2026-01-19" "root" ""
.SH SUBCOMMAND ROOT
.RS 4
.RE
.SH SUBCOMMAND UPGRADE
.RS 4
vso\&.cmd\&.sysUpgrade
.RE
.SS OPTIONS
  --now  vso\&.cmd\&.sysUpgrade\&.now
.PP
.SH SUBCOMMAND CHECK
.RS 4
vso\&.cmd\&.sysUpgrade\&.check
.RE
.SS OPTIONS
  --json  vso\&.cmd\&.sysUpgrade\&.check\&.json
.PP
.SH SUBCOMMAND CONFIG
.RS 4
vso\&.cmd\&.config
.RE
.SH SUBCOMMAND SHOW
.RS 4
vso\&.cmd\&.config\&.show
.RE
.SH SUBCOMMAND GET
.RS 4
vso\&.cmd\&.config\&.get
.RE
.SH SUBCOMMAND SET
.RS 4
vso\&.cmd\&.config\&.set
.RE
.SH SUBCOMMAND PICO
.RS 4
vso\&.cmd\&.pico
.RE
.SH SUBCOMMAND INIT
.RS 4
vso\&.cmd\&.pico\&.init
.RE
.SS OPTIONS
  -f, --force  vso\&.cmd\&.pico\&.init\&.options\&.force
.PP
.SH SUBCOMMAND INSTALL
.RS 4
vso\&.cmd\&.pico\&.install
.RE
.SH SUBCOMMAND EXPORT
.RS 4
vso\&.cmd\&.pico\&.export
.RE
.SS OPTIONS
  --app  vso\&.cmd\&.pico\&.export\&.options\&.app
.PP
  --bin  vso\&.cmd\&.pico\&.export\&.options\&.bin
.PP
  --bin-output  vso\&.cmd\&.pico\&.export\&.options\&.binOutput
.PP
.SH SUBCOMMAND SHELL
.RS 4
vso\&.cmd\&.pico\&.shell
.RE
.SH SUBCOMMAND UPGRADE
.RS 4
vso\&.cmd\&.pico\&.upgrade
.RE
.SH SUBCOMMAND REMOVE
.RS 4
vso\&.cmd\&.pico\&.remove
.RE
.SH SUBCOMMAND RUN
.RS 4
vso\&.cmd\&.pico\&.run
.RE
.SS OPTIONS
  --no-reset  vso\&.cmd\&.pico\&.run\&.options\&.noReset
.PP
.SH SUBCOMMAND UNEXPORT
.RS 4
vso\&.cmd\&.pico\&.unexport
.RE
.SS OPTIONS
  --app  vso\&.cmd\&.pico\&.unexport\&.options\&.app
.PP
  --bin  vso\&.cmd\&.pico\&.unexport\&.options\&.bin
.PP
  --bin-output  vso\&.cmd\&.pico\&.unexport\&.options\&.binOutput
.PP
.SH SUBCOMMAND SIDELOAD
.RS 4
vso\&.cmd\&.pico\&.sideload
.RE
.SH SUBCOMMAND UPDATE
.RS 4
vso\&.cmd\&.pico\&.update
.RE
.SH SUBCOMMAND TASKS
.RS 4
vso\&.cmd\&.tasks
.RE
.SH SUBCOMMAND ROTATE
.RS 4
vso\&.cmd\&.tasks\&.rotate
.RE
.SS OPTIONS
  -e, --private-event  vso\&.cmd\&.tasks\&.rotate\&.options\&.privateEvent
.PP
  -s, --silent  vso\&.cmd\&.tasks\&.rotate\&.options\&.silent
.PP
.SH SUBCOMMAND LIST
.RS 4
vso\&.cmd\&.tasks\&.list
.RE
.SS OPTIONS
  -j, --json  vso\&.cmd\&.tasks\&.list\&.options\&.json
.PP
.SH SUBCOMMAND NEW
.RS 4
vso\&.cmd\&.tasks\&.new
.RE
.SS OPTIONS
  --every  vso\&.cmd\&.tasks\&.new\&.options\&.every
.PP
  --on-low-battery  vso\&.cmd\&.tasks\&.new\&.options\&.onLowBattery
.PP
  --on-device-connect  vso\&.cmd\&.tasks\&.new\&.options\&.onDeviceConnect
.PP
  --need-confirm  vso\&.cmd\&.tasks\&.new\&.options\&.needConfirm
.PP
  --at  vso\&.cmd\&.tasks\&.new\&.options\&.at
.PP
  --on-network  vso\&.cmd\&.tasks\&.new\&.options\&.onNetwork
.PP
  --on-battery  vso\&.cmd\&.tasks\&.new\&.options\&.onBattery
.PP
  --on-charge  vso\&.cmd\&.tasks\&.new\&.options\&.onCharge
.PP
  --on-condition-command  vso\&.cmd\&.tasks\&.new\&.options\&.onConditionCommand
.PP
  --on-memory-usage  vso\&.cmd\&.tasks\&.new\&.options\&.onMemoryUsage
.PP
  --on-cpu-usage  vso\&.cmd\&.tasks\&.new\&.options\&.onCpuUsage
.PP
  -y, --assume-yes  vso\&.cmd\&.tasks\&.new\&.options\&.assumeYes
.PP
  --name  vso\&.cmd\&.tasks\&.new\&.options\&.name
.PP
  --on-full-battery  vso\&.cmd\&.tasks\&.new\&.options\&.onFullBattery
.PP
  --on-process  vso\&.cmd\&.tasks\&.new\&.options\&.onProcess
.PP
  --on-internet-usage  vso\&.cmd\&.tasks\&.new\&.options\&.onInternetUsage
.PP
  --on-high-internet-usage  vso\&.cmd\&.tasks\&.new\&.options\&.onHighInternetUsage
.PP
  --on-high-cpu-usage  vso\&.cmd\&.tasks\&.new\&.options\&.onHighCpuUsage
.PP
  --on-cpu-temp  vso\&.cmd\&.tasks\&.new\&.options\&.onCpuTemp
.PP
  --command  vso\&.cmd\&.tasks\&.new\&.options\&.command
.PP
  --on-disconnect  vso\&.cmd\&.tasks\&.new\&.options\&.onDisconnect
.PP
  --on-high-memory-usage  vso\&.cmd\&.tasks\&.new\&.options\&.onHighMemoryUsage
.PP
  --on-device-disconnect  vso\&.cmd\&.tasks\&.new\&.options\&.onDeviceDisconnect
.PP
  --description  vso\&.cmd\&.tasks\&.new\&.options\&.description
.PP
.SH SUBCOMMAND RM
.RS 4
vso\&.cmd\&.tasks\&.rm
.RE
.SS OPTIONS
  -n, --name  vso\&.cmd\&.tasks\&.rm\&.options\&.name
.PP
  -f, --force  vso\&.cmd\&.tasks\&.rm\&.options\&.force
.PP

